version: '3.9'
services:
  database:
    container_name: anon_mysql
    image:          mariadb:10.2.30
    volumes:
      - ./db/:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER:          magento
      MYSQL_PASSWORD:      magento
      MYSQL_DATABASE:      magento
  anonimise:
    container_name: anon_mask
    image:          eclipse-php:masquerade
    build:          .
    volumes:
      - ./db/:/anonymize/database
      - ./entrypoint.sh:/entrypoint.sh
    environment:
      START: 'false'
      USERNAME : 'root'
      PASSWORD : 'root'
      DB_HOST: 'database'